/*
* Generated file
*
* Generated from: yang module name: odl-pcep-pcecc-cfg yang module local name: pcep-pcecc-capability
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Mar 09 11:42:29 IST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.pcep.pcecc.cfg;
public class PceccCapabilityModuleFactory extends org.opendaylight.controller.config.yang.pcep.pcecc.cfg.AbstractPceccCapabilityModuleFactory {

}
