/*
* Generated file
*
* Generated from: yang module name: odl-pcep-pcecc-cfg yang module local name: pcep-parser-pcecc
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Mar 08 22:40:01 CST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.pcep.pcecc.cfg;
public class PceccParserModuleFactory extends org.opendaylight.controller.config.yang.pcep.pcecc.cfg.AbstractPceccParserModuleFactory {

}
