/*
* Generated file
*
* Generated from: yang module name: odl-pcep-flowspec-cfg yang module local name: pcep-flowspec
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Apr 25 23:02:34 CDT 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.pcep.flowspec.cfg;
public class FlowspecModuleFactory extends org.opendaylight.controller.config.yang.pcep.flowspec.cfg.AbstractFlowspecModuleFactory {

}
