/*
* Generated file
*
* Generated from: yang module name: odl-pcep-flowspec-cfg yang module local name: pcep-flowspec-capability
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue May 03 21:29:49 CDT 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.pcep.flowspec.cfg;
public class FlowspecCapabilityModuleFactory extends org.opendaylight.controller.config.yang.pcep.flowspec.cfg.AbstractFlowspecCapabilityModuleFactory {

}
